version: '3.8'

services:
  mongo-test:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=mythayun_test
    ports:
      - "27017:27017"
    volumes:
      - mongo-test-data:/data/db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./reports:/app/reports
      - ./coverage:/app/coverage
    environment:
      - NODE_ENV=test
      - CI=true
      - DATABASE_URL=mongodb://mongo-test:27017/mythayun_test
      - JWT_SECRET=${JWT_SECRET:-test_secret}
      - JWT_EXPIRY=${JWT_EXPIRY:-1d}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - JWT_ISSUER=${JWT_ISSUER:-test.mythayun.com}
    depends_on:
      mongo-test:
        condition: service_healthy
    command: npm run test:ci

volumes:
  mongo-test-data: