version: '3.8'

services:
  app-test:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    command: npm run test
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongo-test:27017/mythayun_test
    depends_on:
      mongo-test:
        condition: service_healthy
    networks:
      - mythayun-test-network
  
  mongo-test:
    image: mongo:6
    ports:
      - "27018:27017"
    tmpfs:
      - /data/db
    networks:
      - mythayun-test-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/mythayun_test --quiet
      interval: 5s
      timeout: 3s
      retries: 5
  
  e2e-test:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    command: npm run test:e2e
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongo-test:27017/mythayun_test
      - APP_URL=http://app-test:3000
    depends_on:
      - app-test
      - mongo-test
    networks:
      - mythayun-test-network

networks:
  mythayun-test-network:
    driver: bridge