version: '3.8'

services:
  app:
    build:
      context: .
      target: deps
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/mythayun
    depends_on:
      - mongodb
    networks:
      - mythayun-network
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mythayun-network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/mythayun --quiet
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mythayun-network:
    driver: bridge

volumes:
  node_modules:
  mongodb_data: